//
//  SceneId.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2022 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {

	[Preserve]
	public enum SceneId {
		NietzscheGameMain,
		NietzscheGameBoot,
		IlmparkGameBoot,
		IlmparkGameMain,
		IlmparkGameAr,
		ViewerBoot,
		ViewerArBoot,
		NietzscheDeathChamberBoot,
		NietzscheDeathChamber_1903,
		NietzscheDeathChamber_1926,
		NietzscheDeathChamber_1956,
		NietzscheDeathChamberToday,
		AnnaAmaliaBooksBoot,
		AnnaAmaliaBooksSauerBible,
		AnnaAmaliaBooksJosephusopera,
		AnnaAmaliaBooksHistoireDeJulesCesar,
		AnnaAmaliaBooksTabularium,
		AnnaAmaliaBooksSynodus,
		AnnaAmaliaBooksDeStatuReligionis
	}

	[Preserve]
	public class SceneIdConverter : JsonConverter
	{

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
		{
			SceneId castedValue = (SceneId)value;
			switch (castedValue)
			{
				case SceneId.NietzscheGameMain:
					writer.WriteValue("NIETZSCHE_GAME_MAIN");break;
				case SceneId.NietzscheGameBoot:
					writer.WriteValue("NIETZSCHE_GAME_BOOT");break;
				case SceneId.IlmparkGameBoot:
					writer.WriteValue("ILMPARK_GAME_BOOT");break;
				case SceneId.IlmparkGameMain:
					writer.WriteValue("ILMPARK_GAME_MAIN");break;
				case SceneId.IlmparkGameAr:
					writer.WriteValue("ILMPARK_GAME_AR");break;
				case SceneId.ViewerBoot:
					writer.WriteValue("VIEWER_BOOT");break;
				case SceneId.ViewerArBoot:
					writer.WriteValue("VIEWER_AR_BOOT");break;
				case SceneId.NietzscheDeathChamberBoot:
					writer.WriteValue("NIETZSCHE_DEATH_CHAMBER_BOOT");break;
				case SceneId.NietzscheDeathChamber_1903:
					writer.WriteValue("NIETZSCHE_DEATH_CHAMBER_1903");break;
				case SceneId.NietzscheDeathChamber_1926:
					writer.WriteValue("NIETZSCHE_DEATH_CHAMBER_1926");break;
				case SceneId.NietzscheDeathChamber_1956:
					writer.WriteValue("NIETZSCHE_DEATH_CHAMBER_1956");break;
				case SceneId.NietzscheDeathChamberToday:
					writer.WriteValue("NIETZSCHE_DEATH_CHAMBER_TODAY");break;
				case SceneId.AnnaAmaliaBooksBoot:
					writer.WriteValue("ANNA_AMALIA_BOOKS_BOOT");break;
				case SceneId.AnnaAmaliaBooksSauerBible:
					writer.WriteValue("ANNA_AMALIA_BOOKS_SAUER_BIBLE");break;
				case SceneId.AnnaAmaliaBooksJosephusopera:
					writer.WriteValue("ANNA_AMALIA_BOOKS_JOSEPHUSOPERA");break;
				case SceneId.AnnaAmaliaBooksHistoireDeJulesCesar:
					writer.WriteValue("ANNA_AMALIA_BOOKS_HISTOIRE_DE_JULES_CESAR");break;
				case SceneId.AnnaAmaliaBooksTabularium:
					writer.WriteValue("ANNA_AMALIA_BOOKS_TABULARIUM");break;
				case SceneId.AnnaAmaliaBooksSynodus:
					writer.WriteValue("ANNA_AMALIA_BOOKS_SYNODUS");break;
				case SceneId.AnnaAmaliaBooksDeStatuReligionis:
					writer.WriteValue("ANNA_AMALIA_BOOKS_DE_STATU_RELIGIONIS");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer)
		{
			var enumString = (string)reader.Value;
			return FromString(enumString);
		}

		public static SceneId? FromString(string enumString)
		{
			switch (enumString)
			{
				case "NIETZSCHE_GAME_MAIN":
					return SceneId.NietzscheGameMain;
				case "NIETZSCHE_GAME_BOOT":
					return SceneId.NietzscheGameBoot;
				case "ILMPARK_GAME_BOOT":
					return SceneId.IlmparkGameBoot;
				case "ILMPARK_GAME_MAIN":
					return SceneId.IlmparkGameMain;
				case "ILMPARK_GAME_AR":
					return SceneId.IlmparkGameAr;
				case "VIEWER_BOOT":
					return SceneId.ViewerBoot;
				case "VIEWER_AR_BOOT":
					return SceneId.ViewerArBoot;
				case "NIETZSCHE_DEATH_CHAMBER_BOOT":
					return SceneId.NietzscheDeathChamberBoot;
				case "NIETZSCHE_DEATH_CHAMBER_1903":
					return SceneId.NietzscheDeathChamber_1903;
				case "NIETZSCHE_DEATH_CHAMBER_1926":
					return SceneId.NietzscheDeathChamber_1926;
				case "NIETZSCHE_DEATH_CHAMBER_1956":
					return SceneId.NietzscheDeathChamber_1956;
				case "NIETZSCHE_DEATH_CHAMBER_TODAY":
					return SceneId.NietzscheDeathChamberToday;
				case "ANNA_AMALIA_BOOKS_BOOT":
					return SceneId.AnnaAmaliaBooksBoot;
				case "ANNA_AMALIA_BOOKS_SAUER_BIBLE":
					return SceneId.AnnaAmaliaBooksSauerBible;
				case "ANNA_AMALIA_BOOKS_JOSEPHUSOPERA":
					return SceneId.AnnaAmaliaBooksJosephusopera;
				case "ANNA_AMALIA_BOOKS_HISTOIRE_DE_JULES_CESAR":
					return SceneId.AnnaAmaliaBooksHistoireDeJulesCesar;
				case "ANNA_AMALIA_BOOKS_TABULARIUM":
					return SceneId.AnnaAmaliaBooksTabularium;
				case "ANNA_AMALIA_BOOKS_SYNODUS":
					return SceneId.AnnaAmaliaBooksSynodus;
				case "ANNA_AMALIA_BOOKS_DE_STATU_RELIGIONIS":
					return SceneId.AnnaAmaliaBooksDeStatuReligionis;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType)
		{
			return objectType == typeof(string);
		}
	}

	[Preserve]
	public static class SceneIdExtensions
	{
		public static string RawValue(this SceneId value)
		{
			switch (value)
			{
				case SceneId.NietzscheGameMain:
					return "NIETZSCHE_GAME_MAIN";
				case SceneId.NietzscheGameBoot:
					return "NIETZSCHE_GAME_BOOT";
				case SceneId.IlmparkGameBoot:
					return "ILMPARK_GAME_BOOT";
				case SceneId.IlmparkGameMain:
					return "ILMPARK_GAME_MAIN";
				case SceneId.IlmparkGameAr:
					return "ILMPARK_GAME_AR";
				case SceneId.ViewerBoot:
					return "VIEWER_BOOT";
				case SceneId.ViewerArBoot:
					return "VIEWER_AR_BOOT";
				case SceneId.NietzscheDeathChamberBoot:
					return "NIETZSCHE_DEATH_CHAMBER_BOOT";
				case SceneId.NietzscheDeathChamber_1903:
					return "NIETZSCHE_DEATH_CHAMBER_1903";
				case SceneId.NietzscheDeathChamber_1926:
					return "NIETZSCHE_DEATH_CHAMBER_1926";
				case SceneId.NietzscheDeathChamber_1956:
					return "NIETZSCHE_DEATH_CHAMBER_1956";
				case SceneId.NietzscheDeathChamberToday:
					return "NIETZSCHE_DEATH_CHAMBER_TODAY";
				case SceneId.AnnaAmaliaBooksBoot:
					return "ANNA_AMALIA_BOOKS_BOOT";
				case SceneId.AnnaAmaliaBooksSauerBible:
					return "ANNA_AMALIA_BOOKS_SAUER_BIBLE";
				case SceneId.AnnaAmaliaBooksJosephusopera:
					return "ANNA_AMALIA_BOOKS_JOSEPHUSOPERA";
				case SceneId.AnnaAmaliaBooksHistoireDeJulesCesar:
					return "ANNA_AMALIA_BOOKS_HISTOIRE_DE_JULES_CESAR";
				case SceneId.AnnaAmaliaBooksTabularium:
					return "ANNA_AMALIA_BOOKS_TABULARIUM";
				case SceneId.AnnaAmaliaBooksSynodus:
					return "ANNA_AMALIA_BOOKS_SYNODUS";
				case SceneId.AnnaAmaliaBooksDeStatuReligionis:
					return "ANNA_AMALIA_BOOKS_DE_STATU_RELIGIONIS";
				default:
					return null;
			}

		}

	}}
