//
//  ApiError.cs
//  GuidePilot
//
//  All GuidePilot API error codes
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum ApiError: int {
		BadRequest = 400000,
		Unauthorized = 401000,
		Forbidden = 403000,
		NotFound = 404000,
		NotFoundInApiVersion = 404100,
		Conflict = 409000,
		Duplicate = 409100,
		InternalServerError = 500000,
		Teapot = 418000,
		DevilsTeapod = 418666,
}
}
