//
//  Domain.cs
//  GuidePilot
//
//  Describes the belonging of the entity.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum Domain {
		Cms,
		Plugin,
		System
	}

	[Preserve]
	public class DomainConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			Domain castedValue = (Domain)value;
			switch (castedValue) {
			case Domain.Cms:
			writer.WriteValue("CMS");break;
			case Domain.Plugin:
			writer.WriteValue("PLUGIN");break;
			case Domain.System:
			writer.WriteValue("SYSTEM");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "CMS":
			return Domain.Cms;
			case "PLUGIN":
			return Domain.Plugin;
			case "SYSTEM":
			return Domain.System;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
