//
//  GatewayType.cs
//  GuidePilot
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum GatewayType {
		Apns,
		Fcm
	}

	[Preserve]
	public class GatewayTypeConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			GatewayType castedValue = (GatewayType)value;
			switch (castedValue) {
			case GatewayType.Apns:
			writer.WriteValue("APNS");break;
			case GatewayType.Fcm:
			writer.WriteValue("FCM");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "APNS":
			return GatewayType.Apns;
			case "FCM":
			return GatewayType.Fcm;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
