//
//  MediaType.cs
//  GuidePilot
//
//  This is the first part of the mime type.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum MediaType {
		Audio,
		Video,
		Image,
		Text,
		Font,
		Application
	}

	[Preserve]
	public class MediaTypeConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			MediaType castedValue = (MediaType)value;
			switch (castedValue) {
			case MediaType.Audio:
			writer.WriteValue("AUDIO");break;
			case MediaType.Video:
			writer.WriteValue("VIDEO");break;
			case MediaType.Image:
			writer.WriteValue("IMAGE");break;
			case MediaType.Text:
			writer.WriteValue("TEXT");break;
			case MediaType.Font:
			writer.WriteValue("FONT");break;
			case MediaType.Application:
			writer.WriteValue("APPLICATION");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "AUDIO":
			return MediaType.Audio;
			case "VIDEO":
			return MediaType.Video;
			case "IMAGE":
			return MediaType.Image;
			case "TEXT":
			return MediaType.Text;
			case "FONT":
			return MediaType.Font;
			case "APPLICATION":
			return MediaType.Application;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
