//
//  Platform.cs
//  GuidePilot
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum Platform {
		Android,
		Ios
	}

	[Preserve]
	public class PlatformConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			Platform castedValue = (Platform)value;
			switch (castedValue) {
			case Platform.Android:
			writer.WriteValue("ANDROID");break;
			case Platform.Ios:
			writer.WriteValue("IOS");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "ANDROID":
			return Platform.Android;
			case "IOS":
			return Platform.Ios;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
