//
//  PushSubscribeTo.cs
//  GuidePilot
//
//  The allowed values for the additional subscribe_to value
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum PushSubscribeTo {
		Default,
		Test
	}

	[Preserve]
	public class PushSubscribeToConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			PushSubscribeTo castedValue = (PushSubscribeTo)value;
			switch (castedValue) {
			case PushSubscribeTo.Default:
			writer.WriteValue("DEFAULT");break;
			case PushSubscribeTo.Test:
			writer.WriteValue("TEST");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "DEFAULT":
			return PushSubscribeTo.Default;
			case "TEST":
			return PushSubscribeTo.Test;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
