//
//  Visibility.cs
//  GuidePilot
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using Newtonsoft.Json;
using UnityEngine.Scripting;

namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public enum Visibility {
		Never,
		Always
	}

	[Preserve]
	public class VisibilityConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			Visibility castedValue = (Visibility)value;
			switch (castedValue) {
			case Visibility.Never:
			writer.WriteValue("NEVER");break;
			case Visibility.Always:
			writer.WriteValue("ALWAYS");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "NEVER":
			return Visibility.Never;
			case "ALWAYS":
			return Visibility.Always;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}}
