//
//  ActorDocument.cs
//  GuidePilot
//
//  Actor document
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class ActorDocument: CoreObject, DocumentRelation {
	//  Describes the relation of the document to the actor.

	[Preserve]
	public enum Relation {
		Biography,
		Portrait
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			ActorDocument.Relation castedValue = (ActorDocument.Relation)value;
			switch (castedValue) {
			case ActorDocument.Relation.Biography:
			writer.WriteValue("BIOGRAPHY");break;
			case ActorDocument.Relation.Portrait:
			writer.WriteValue("PORTRAIT");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "BIOGRAPHY":
			return ActorDocument.Relation.Biography;
			case "PORTRAIT":
			return ActorDocument.Relation.Portrait;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}