//
//  AppInfoEvent.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class AppInfoEvent: ContextEvent {
	//  

	[Preserve]
	public enum Verb {
		Launched
	}

	[Preserve]
	public class VerbConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			AppInfoEvent.Verb castedValue = (AppInfoEvent.Verb)value;
			switch (castedValue) {
			case AppInfoEvent.Verb.Launched:
			writer.WriteValue("LAUNCHED");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "LAUNCHED":
			return AppInfoEvent.Verb.Launched;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

[JsonConverter(typeof(DictionaryConverter))]
	[JsonProperty("custom_data")]
	private Dictionary<string, object> internCustomData;
	[JsonIgnore]
	public Dictionary<string, object> customData { get => internCustomData; set => internCustomData = value; }
	[JsonProperty("timestamp")]
	private DateTime internTimestamp;
	[JsonIgnore]
	public DateTime timestamp { get => internTimestamp; set => internTimestamp = value; }
	[JsonProperty("collision_hash")]
	private string internCollisionHash;
	[JsonIgnore]
	public string collisionHash { get => internCollisionHash; set => internCollisionHash = value; }
	[JsonProperty("session_uuid")]
	private string internSessionUuid;
	[JsonIgnore]
	public string sessionUuid { get => internSessionUuid; set => internSessionUuid = value; }
	[JsonProperty("installation_uuid")]
	private string internInstallationUuid;
	[JsonIgnore]
	public string installationUuid { get => internInstallationUuid; set => internInstallationUuid = value; }
[JsonConverter(typeof(VerbConverter))]
	[JsonProperty("verb")]
	public Verb verb;
	[JsonProperty("app_version")]
	public string appVersion;
[JsonConverter(typeof(PlatformConverter))]
	[JsonProperty("platform")]
	public Platform platform;
	[JsonProperty("os_version")]
	public string osVersion;
	[JsonProperty("device")]
	public string device;
	[JsonProperty("system_locale")]
	public string systemLocale;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"verb:" + verb + Environment.NewLine + 	"appVersion:" + appVersion + Environment.NewLine + 	"platform:" + platform + Environment.NewLine + 	"osVersion:" + osVersion + Environment.NewLine + 	"device:" + device + Environment.NewLine + 	"systemLocale:" + systemLocale + Environment.NewLine);
	}
	}
}