//
//  Building.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class Building: CoreLinkable, CoreObject, Placed, Tagged, Titled {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("geo_lat")]
	private double internGeoLat;
	[JsonIgnore]
	public double geoLat { get => internGeoLat; set => internGeoLat = value; }
	[JsonProperty("geo_long")]
	private double internGeoLong;
	[JsonIgnore]
	public double geoLong { get => internGeoLong; set => internGeoLong = value; }
	[JsonProperty("tags")]
	private string[] internTags;
	[JsonIgnore]
	public string[] tags { get => internTags; set => internTags = value; }
	[JsonProperty("title")]
	private Dictionary<string, object> internTitle;
	[JsonIgnore]
	public Dictionary<string, object> title { get => internTitle; set => internTitle = value; }
	[JsonProperty("title_short")]
	private Dictionary<string, object> internTitleShort;
	[JsonIgnore]
	public Dictionary<string, object> titleShort { get => internTitleShort; set => internTitleShort = value; }
	[JsonProperty("rotation")]
	public int? rotation;
	[JsonProperty("entrances")]
	public Entrance[] entrances;
	[JsonProperty("building_documents")]
	public BuildingDocument[] buildingDocuments;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"rotation:" + rotation + Environment.NewLine + 	"entrances:" + entrances + Environment.NewLine + 	"buildingDocuments:" + buildingDocuments + Environment.NewLine);
	}
	}
}