//
//  BuildingDocument.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class BuildingDocument: CoreObject, DocumentRelation {
	[Preserve]
	public enum Relation {
		Media,
		Plan,
		MapIcon,
		SameLocationInfo
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			BuildingDocument.Relation castedValue = (BuildingDocument.Relation)value;
			switch (castedValue) {
			case BuildingDocument.Relation.Media:
			writer.WriteValue("MEDIA");break;
			case BuildingDocument.Relation.Plan:
			writer.WriteValue("PLAN");break;
			case BuildingDocument.Relation.MapIcon:
			writer.WriteValue("MAP_ICON");break;
			case BuildingDocument.Relation.SameLocationInfo:
			writer.WriteValue("SAME_LOCATION_INFO");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "MEDIA":
			return BuildingDocument.Relation.Media;
			case "PLAN":
			return BuildingDocument.Relation.Plan;
			case "MAP_ICON":
			return BuildingDocument.Relation.MapIcon;
			case "SAME_LOCATION_INFO":
			return BuildingDocument.Relation.SameLocationInfo;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}