//
//  CalendarEventInfo.cs
//  GuidePilot
//
//  Container element wrapping all occurrences of a event together with it's infos
//  and documents
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class CalendarEventInfo: CoreLinkable, CoreObject, Subtitled, Titled {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("subtitle")]
	private Dictionary<string, object> internSubtitle;
	[JsonIgnore]
	public Dictionary<string, object> subtitle { get => internSubtitle; set => internSubtitle = value; }
	[JsonProperty("subtitle_short")]
	private Dictionary<string, object> internSubtitleShort;
	[JsonIgnore]
	public Dictionary<string, object> subtitleShort { get => internSubtitleShort; set => internSubtitleShort = value; }
	[JsonProperty("title")]
	private Dictionary<string, object> internTitle;
	[JsonIgnore]
	public Dictionary<string, object> title { get => internTitle; set => internTitle = value; }
	[JsonProperty("title_short")]
	private Dictionary<string, object> internTitleShort;
	[JsonIgnore]
	public Dictionary<string, object> titleShort { get => internTitleShort; set => internTitleShort = value; }
	[JsonProperty("calendar_event_info_documents")]
	public CalendarEventInfoDocument[] calendarEventInfoDocuments;
	[JsonProperty("calendar_events")]
	public CalendarEvent[] calendarEvents;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"calendarEventInfoDocuments:" + calendarEventInfoDocuments + Environment.NewLine + 	"calendarEvents:" + calendarEvents + Environment.NewLine);
	}
	}
}