//
//  CalendarLocation.cs
//  GuidePilot
//
//  describes the location of a calendar event (via calendar tags)
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class CalendarLocation: Addressed, CoreLinkable, CoreObject, Titled {
	[JsonProperty("addr_street")]
	private string internAddrStreet;
	[JsonIgnore]
	public string addrStreet { get => internAddrStreet; set => internAddrStreet = value; }
	[JsonProperty("addr_zip_code")]
	private string internAddrZipCode;
	[JsonIgnore]
	public string addrZipCode { get => internAddrZipCode; set => internAddrZipCode = value; }
	[JsonProperty("addr_city")]
	private string internAddrCity;
	[JsonIgnore]
	public string addrCity { get => internAddrCity; set => internAddrCity = value; }
	[JsonProperty("addr_country")]
	private string internAddrCountry;
	[JsonIgnore]
	public string addrCountry { get => internAddrCountry; set => internAddrCountry = value; }
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("title")]
	private Dictionary<string, object> internTitle;
	[JsonIgnore]
	public Dictionary<string, object> title { get => internTitle; set => internTitle = value; }
	[JsonProperty("title_short")]
	private Dictionary<string, object> internTitleShort;
	[JsonIgnore]
	public Dictionary<string, object> titleShort { get => internTitleShort; set => internTitleShort = value; }
	public void print() {
		Debug.Log("object:" + Environment.NewLine);
	}
	}
}