//
//  ContentDocument.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class ContentDocument: CoreObject, DocumentRelation {
	//  Describes the relation of the a document to the content.

	[Preserve]
	public enum Relation {
		Media,
		InventoryMedia,
		PreviewImage,
		ExploreMedia,
		Description,
		CorrectChoiceMedia,
		IncorrectChoiceMedia,
		CorrectEvaluationMedia,
		IncorrectEvaluationMedia,
		SearchTaskMedia
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			ContentDocument.Relation castedValue = (ContentDocument.Relation)value;
			switch (castedValue) {
			case ContentDocument.Relation.Media:
			writer.WriteValue("MEDIA");break;
			case ContentDocument.Relation.InventoryMedia:
			writer.WriteValue("INVENTORY_MEDIA");break;
			case ContentDocument.Relation.PreviewImage:
			writer.WriteValue("PREVIEW_IMAGE");break;
			case ContentDocument.Relation.ExploreMedia:
			writer.WriteValue("EXPLORE_MEDIA");break;
			case ContentDocument.Relation.Description:
			writer.WriteValue("DESCRIPTION");break;
			case ContentDocument.Relation.CorrectChoiceMedia:
			writer.WriteValue("CORRECT_CHOICE_MEDIA");break;
			case ContentDocument.Relation.IncorrectChoiceMedia:
			writer.WriteValue("INCORRECT_CHOICE_MEDIA");break;
			case ContentDocument.Relation.CorrectEvaluationMedia:
			writer.WriteValue("CORRECT_EVALUATION_MEDIA");break;
			case ContentDocument.Relation.IncorrectEvaluationMedia:
			writer.WriteValue("INCORRECT_EVALUATION_MEDIA");break;
			case ContentDocument.Relation.SearchTaskMedia:
			writer.WriteValue("SEARCH_TASK_MEDIA");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "MEDIA":
			return ContentDocument.Relation.Media;
			case "INVENTORY_MEDIA":
			return ContentDocument.Relation.InventoryMedia;
			case "PREVIEW_IMAGE":
			return ContentDocument.Relation.PreviewImage;
			case "EXPLORE_MEDIA":
			return ContentDocument.Relation.ExploreMedia;
			case "DESCRIPTION":
			return ContentDocument.Relation.Description;
			case "CORRECT_CHOICE_MEDIA":
			return ContentDocument.Relation.CorrectChoiceMedia;
			case "INCORRECT_CHOICE_MEDIA":
			return ContentDocument.Relation.IncorrectChoiceMedia;
			case "CORRECT_EVALUATION_MEDIA":
			return ContentDocument.Relation.CorrectEvaluationMedia;
			case "INCORRECT_EVALUATION_MEDIA":
			return ContentDocument.Relation.IncorrectEvaluationMedia;
			case "SEARCH_TASK_MEDIA":
			return ContentDocument.Relation.SearchTaskMedia;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}