//
//  CustomTrigger.cs
//  GuidePilot
//
//  Trigger a zone by external reference
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class CustomTrigger: CoreLinkable, CoreObject {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("external_reference")]
	public string externalReference;
	[JsonProperty("gp_zone_id")]
	public int gpZoneId;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"externalReference:" + externalReference + Environment.NewLine + 	"gpZoneId:" + gpZoneId + Environment.NewLine);
	}
	}
}