//
//  DocumentProperty.cs
//  GuidePilot
//
//  Adds optional user presentable (not technical) key value like properties to
//  documents.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class DocumentProperty: CoreObject, Sorted {
	//  Describes the meaning of the document property.

	[Preserve]
	public enum Type {
		OriginalTitle,
		Description,
		Copyright,
		Credits,
		AdditionalInformation
	}

	[Preserve]
	public class TypeConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			DocumentProperty.Type castedValue = (DocumentProperty.Type)value;
			switch (castedValue) {
			case DocumentProperty.Type.OriginalTitle:
			writer.WriteValue("ORIGINAL_TITLE");break;
			case DocumentProperty.Type.Description:
			writer.WriteValue("DESCRIPTION");break;
			case DocumentProperty.Type.Copyright:
			writer.WriteValue("COPYRIGHT");break;
			case DocumentProperty.Type.Credits:
			writer.WriteValue("CREDITS");break;
			case DocumentProperty.Type.AdditionalInformation:
			writer.WriteValue("ADDITIONAL_INFORMATION");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "ORIGINAL_TITLE":
			return DocumentProperty.Type.OriginalTitle;
			case "DESCRIPTION":
			return DocumentProperty.Type.Description;
			case "COPYRIGHT":
			return DocumentProperty.Type.Copyright;
			case "CREDITS":
			return DocumentProperty.Type.Credits;
			case "ADDITIONAL_INFORMATION":
			return DocumentProperty.Type.AdditionalInformation;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("sort_index")]
	private int internSortIndex;
	[JsonIgnore]
	public int sortIndex { get => internSortIndex; set => internSortIndex = value; }
[JsonConverter(typeof(TypeConverter))]
	[JsonProperty("type")]
	public Type type;
[JsonConverter(typeof(DataTypeConverter))]
	[JsonProperty("data_type")]
	public DataType dataType;
	[JsonProperty("value")]
	public Dictionary<string, object> value;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"type:" + type + Environment.NewLine + 	"dataType:" + dataType + Environment.NewLine + 	"value:" + value + Environment.NewLine);
	}
	}
}