//
//  DocumentCache.cs
//  GuidePilot
//
//  For management of the downloaded documents and their metadata.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class DocumentCache {
	[JsonProperty("e_tag")]
	public string eTag;
	[JsonProperty("urls")]
	public DocumentCacheUrl[] urls;
	[JsonProperty("last_server_check")]
	public DateTime lastServerCheck;
	[JsonProperty("last_usage")]
	public DateTime lastUsage;
	[JsonProperty("file_size")]
	public long fileSize;
	[JsonProperty("file_name")]
	public string fileName;
	[JsonProperty("last_checked_main_package_id")]
	public string lastCheckedMainPackageId;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"eTag:" + eTag + Environment.NewLine + 	"urls:" + urls + Environment.NewLine + 	"lastServerCheck:" + lastServerCheck + Environment.NewLine + 	"lastUsage:" + lastUsage + Environment.NewLine + 	"fileSize:" + fileSize + Environment.NewLine + 	"fileName:" + fileName + Environment.NewLine + 	"lastCheckedMainPackageId:" + lastCheckedMainPackageId + Environment.NewLine);
	}
	}
}