//
//  DocumentEvent.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class DocumentEvent: EntityEvent, LocaleEvent {
	//  

	[Preserve]
	public enum Verb {
		Appeared,
		PreviewAppeared,
		Started,
		Ended,
		Paused
	}

	[Preserve]
	public class VerbConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			DocumentEvent.Verb castedValue = (DocumentEvent.Verb)value;
			switch (castedValue) {
			case DocumentEvent.Verb.Appeared:
			writer.WriteValue("APPEARED");break;
			case DocumentEvent.Verb.PreviewAppeared:
			writer.WriteValue("PREVIEW_APPEARED");break;
			case DocumentEvent.Verb.Started:
			writer.WriteValue("STARTED");break;
			case DocumentEvent.Verb.Ended:
			writer.WriteValue("ENDED");break;
			case DocumentEvent.Verb.Paused:
			writer.WriteValue("PAUSED");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "APPEARED":
			return DocumentEvent.Verb.Appeared;
			case "PREVIEW_APPEARED":
			return DocumentEvent.Verb.PreviewAppeared;
			case "STARTED":
			return DocumentEvent.Verb.Started;
			case "ENDED":
			return DocumentEvent.Verb.Ended;
			case "PAUSED":
			return DocumentEvent.Verb.Paused;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

[JsonConverter(typeof(DictionaryConverter))]
	[JsonProperty("custom_data")]
	private Dictionary<string, object> internCustomData;
	[JsonIgnore]
	public Dictionary<string, object> customData { get => internCustomData; set => internCustomData = value; }
	[JsonProperty("timestamp")]
	private DateTime internTimestamp;
	[JsonIgnore]
	public DateTime timestamp { get => internTimestamp; set => internTimestamp = value; }
	[JsonProperty("collision_hash")]
	private string internCollisionHash;
	[JsonIgnore]
	public string collisionHash { get => internCollisionHash; set => internCollisionHash = value; }
	[JsonProperty("session_uuid")]
	private string internSessionUuid;
	[JsonIgnore]
	public string sessionUuid { get => internSessionUuid; set => internSessionUuid = value; }
	[JsonProperty("installation_uuid")]
	private string internInstallationUuid;
	[JsonIgnore]
	public string installationUuid { get => internInstallationUuid; set => internInstallationUuid = value; }
	[JsonProperty("entity_suuid")]
	private string internEntitySuuid;
	[JsonIgnore]
	public string entitySuuid { get => internEntitySuuid; set => internEntitySuuid = value; }
	[JsonProperty("main_package_revision")]
	private string internMainPackageRevision;
	[JsonIgnore]
	public string mainPackageRevision { get => internMainPackageRevision; set => internMainPackageRevision = value; }
	[JsonProperty("locale")]
	private string internLocale;
	[JsonIgnore]
	public string locale { get => internLocale; set => internLocale = value; }
[JsonConverter(typeof(VerbConverter))]
	[JsonProperty("verb")]
	public Verb verb;
	[JsonProperty("image_size_class_value")]
	public int? imageSizeClassValue;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"verb:" + verb + Environment.NewLine + 	"imageSizeClassValue:" + imageSizeClassValue + Environment.NewLine);
	}
	}
}