//
//  ExhibitionZone.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class ExhibitionZone: CoreLinkable, CoreObject, Prioritized, Subtitled, Tagged, Titled {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("subtitle")]
	private Dictionary<string, object> internSubtitle;
	[JsonIgnore]
	public Dictionary<string, object> subtitle { get => internSubtitle; set => internSubtitle = value; }
	[JsonProperty("subtitle_short")]
	private Dictionary<string, object> internSubtitleShort;
	[JsonIgnore]
	public Dictionary<string, object> subtitleShort { get => internSubtitleShort; set => internSubtitleShort = value; }
	[JsonProperty("tags")]
	private string[] internTags;
	[JsonIgnore]
	public string[] tags { get => internTags; set => internTags = value; }
	[JsonProperty("title")]
	private Dictionary<string, object> internTitle;
	[JsonIgnore]
	public Dictionary<string, object> title { get => internTitle; set => internTitle = value; }
	[JsonProperty("title_short")]
	private Dictionary<string, object> internTitleShort;
	[JsonIgnore]
	public Dictionary<string, object> titleShort { get => internTitleShort; set => internTitleShort = value; }
	[JsonProperty("zone_id")]
	public int zoneId;
	[JsonProperty("exhibition_zone_documents")]
	public ExhibitionZoneDocument[] exhibitionZoneDocuments;
	[JsonProperty("exhibition_id")]
	public int exhibitionId;
	[JsonProperty("exhibition_zone_exhibits")]
	public ExhibitionZoneExhibit[] exhibitionZoneExhibits;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"zoneId:" + zoneId + Environment.NewLine + 	"exhibitionZoneDocuments:" + exhibitionZoneDocuments + Environment.NewLine + 	"exhibitionId:" + exhibitionId + Environment.NewLine + 	"exhibitionZoneExhibits:" + exhibitionZoneExhibits + Environment.NewLine);
	}
	}
}