//
//  ExhibitionZoneExhibit.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class ExhibitionZoneExhibit: CoreObject, Prioritized {
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("exhibit_id")]
	public int exhibitId;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"exhibitId:" + exhibitId + Environment.NewLine);
	}
	}
}