//
//  LocationPermissionEvent.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class LocationPermissionEvent: PermissionEvent {
	//  

	[Preserve]
	public enum Verb {
		Granted,
		GrantedBackground,
		GrantedOnce,
		GrantedToday,
		Denied
	}

	[Preserve]
	public class VerbConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			LocationPermissionEvent.Verb castedValue = (LocationPermissionEvent.Verb)value;
			switch (castedValue) {
			case LocationPermissionEvent.Verb.Granted:
			writer.WriteValue("GRANTED");break;
			case LocationPermissionEvent.Verb.GrantedBackground:
			writer.WriteValue("GRANTED_BACKGROUND");break;
			case LocationPermissionEvent.Verb.GrantedOnce:
			writer.WriteValue("GRANTED_ONCE");break;
			case LocationPermissionEvent.Verb.GrantedToday:
			writer.WriteValue("GRANTED_TODAY");break;
			case LocationPermissionEvent.Verb.Denied:
			writer.WriteValue("DENIED");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "GRANTED":
			return LocationPermissionEvent.Verb.Granted;
			case "GRANTED_BACKGROUND":
			return LocationPermissionEvent.Verb.GrantedBackground;
			case "GRANTED_ONCE":
			return LocationPermissionEvent.Verb.GrantedOnce;
			case "GRANTED_TODAY":
			return LocationPermissionEvent.Verb.GrantedToday;
			case "DENIED":
			return LocationPermissionEvent.Verb.Denied;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	//  

	[Preserve]
	public enum Accuracy {
		Precise,
		Unprecise
	}

	[Preserve]
	public class AccuracyConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			LocationPermissionEvent.Accuracy castedValue = (LocationPermissionEvent.Accuracy)value;
			switch (castedValue) {
			case LocationPermissionEvent.Accuracy.Precise:
			writer.WriteValue("PRECISE");break;
			case LocationPermissionEvent.Accuracy.Unprecise:
			writer.WriteValue("UNPRECISE");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "PRECISE":
			return LocationPermissionEvent.Accuracy.Precise;
			case "UNPRECISE":
			return LocationPermissionEvent.Accuracy.Unprecise;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

[JsonConverter(typeof(DictionaryConverter))]
	[JsonProperty("custom_data")]
	private Dictionary<string, object> internCustomData;
	[JsonIgnore]
	public Dictionary<string, object> customData { get => internCustomData; set => internCustomData = value; }
	[JsonProperty("timestamp")]
	private DateTime internTimestamp;
	[JsonIgnore]
	public DateTime timestamp { get => internTimestamp; set => internTimestamp = value; }
	[JsonProperty("collision_hash")]
	private string internCollisionHash;
	[JsonIgnore]
	public string collisionHash { get => internCollisionHash; set => internCollisionHash = value; }
	[JsonProperty("session_uuid")]
	private string internSessionUuid;
	[JsonIgnore]
	public string sessionUuid { get => internSessionUuid; set => internSessionUuid = value; }
	[JsonProperty("installation_uuid")]
	private string internInstallationUuid;
	[JsonIgnore]
	public string installationUuid { get => internInstallationUuid; set => internInstallationUuid = value; }
[JsonConverter(typeof(VerbConverter))]
	[JsonProperty("verb")]
	public Verb verb;
[JsonConverter(typeof(AccuracyConverter))]
	[JsonProperty("accuracy")]
	public Accuracy accuracy;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"verb:" + verb + Environment.NewLine + 	"accuracy:" + accuracy + Environment.NewLine);
	}
	}
}