//
//  MapDocument.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class MapDocument: Bounded, CoreObject, DocumentRelation {
	//  Describes the relation of the a document to the map.

	[Preserve]
	public enum Relation {
		Media,
		Representation
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			MapDocument.Relation castedValue = (MapDocument.Relation)value;
			switch (castedValue) {
			case MapDocument.Relation.Media:
			writer.WriteValue("MEDIA");break;
			case MapDocument.Relation.Representation:
			writer.WriteValue("REPRESENTATION");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "MEDIA":
			return MapDocument.Relation.Media;
			case "REPRESENTATION":
			return MapDocument.Relation.Representation;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("coordinate_left")]
	private double? internCoordinateLeft;
	[JsonIgnore]
	public double? coordinateLeft { get => internCoordinateLeft; set => internCoordinateLeft = value; }
	[JsonProperty("coordinate_bottom")]
	private double? internCoordinateBottom;
	[JsonIgnore]
	public double? coordinateBottom { get => internCoordinateBottom; set => internCoordinateBottom = value; }
	[JsonProperty("coordinate_width")]
	private double? internCoordinateWidth;
	[JsonIgnore]
	public double? coordinateWidth { get => internCoordinateWidth; set => internCoordinateWidth = value; }
	[JsonProperty("coordinate_height")]
	private double? internCoordinateHeight;
	[JsonIgnore]
	public double? coordinateHeight { get => internCoordinateHeight; set => internCoordinateHeight = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}