//
//  MenuEvent.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class MenuEvent: EntityEvent, LocaleEvent {
	//  

	[Preserve]
	public enum Verb {
		Appeared,
		Disappeared
	}

	[Preserve]
	public class VerbConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			MenuEvent.Verb castedValue = (MenuEvent.Verb)value;
			switch (castedValue) {
			case MenuEvent.Verb.Appeared:
			writer.WriteValue("APPEARED");break;
			case MenuEvent.Verb.Disappeared:
			writer.WriteValue("DISAPPEARED");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "APPEARED":
			return MenuEvent.Verb.Appeared;
			case "DISAPPEARED":
			return MenuEvent.Verb.Disappeared;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

[JsonConverter(typeof(DictionaryConverter))]
	[JsonProperty("custom_data")]
	private Dictionary<string, object> internCustomData;
	[JsonIgnore]
	public Dictionary<string, object> customData { get => internCustomData; set => internCustomData = value; }
	[JsonProperty("timestamp")]
	private DateTime internTimestamp;
	[JsonIgnore]
	public DateTime timestamp { get => internTimestamp; set => internTimestamp = value; }
	[JsonProperty("collision_hash")]
	private string internCollisionHash;
	[JsonIgnore]
	public string collisionHash { get => internCollisionHash; set => internCollisionHash = value; }
	[JsonProperty("session_uuid")]
	private string internSessionUuid;
	[JsonIgnore]
	public string sessionUuid { get => internSessionUuid; set => internSessionUuid = value; }
	[JsonProperty("installation_uuid")]
	private string internInstallationUuid;
	[JsonIgnore]
	public string installationUuid { get => internInstallationUuid; set => internInstallationUuid = value; }
	[JsonProperty("entity_suuid")]
	private string internEntitySuuid;
	[JsonIgnore]
	public string entitySuuid { get => internEntitySuuid; set => internEntitySuuid = value; }
	[JsonProperty("main_package_revision")]
	private string internMainPackageRevision;
	[JsonIgnore]
	public string mainPackageRevision { get => internMainPackageRevision; set => internMainPackageRevision = value; }
	[JsonProperty("locale")]
	private string internLocale;
	[JsonIgnore]
	public string locale { get => internLocale; set => internLocale = value; }
[JsonConverter(typeof(VerbConverter))]
	[JsonProperty("verb")]
	public Verb verb;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"verb:" + verb + Environment.NewLine);
	}
	}
}