//
//  PackageInfo.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class PackageInfo: CoreObject {
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("revision")]
	public string revision;
	[JsonProperty("created")]
	public DateTime created;
	[JsonProperty("api_version")]
	public int? apiVersion;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"revision:" + revision + Environment.NewLine + 	"created:" + created + Environment.NewLine + 	"apiVersion:" + apiVersion + Environment.NewLine);
	}
	}
}