//
//  PushIndentity.cs
//  GuidePilot
//
//  describes a push receiver gateway subscription
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class PushIndentity: CoreLinkable, CoreObject {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
[JsonConverter(typeof(GatewayTypeConverter))]
	[JsonProperty("gateway_type")]
	public GatewayType gatewayType;
	[JsonProperty("token")]
	public string token;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"gatewayType:" + gatewayType + Environment.NewLine + 	"token:" + token + Environment.NewLine);
	}
	}
}