//
//  PushReceiver.cs
//  GuidePilot
//
//  describes the users push notification instance stored on the server
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class PushReceiver: CoreLinkable, CoreObject {
	[JsonProperty("suuid")]
	private string internSuuid;
	[JsonIgnore]
	public string suuid { get => internSuuid; set => internSuuid = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("locales")]
	public string[] locales;
	[JsonProperty("push_identities")]
	public PushIndentity[] pushIdentities;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"locales:" + locales + Environment.NewLine + 	"pushIdentities:" + pushIdentities + Environment.NewLine);
	}
	}
}