//
//  ScaleKeypoint.cs
//  GuidePilot
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class ScaleKeypoint: CoreObject, Sorted {
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("sort_index")]
	private int internSortIndex;
	[JsonIgnore]
	public int sortIndex { get => internSortIndex; set => internSortIndex = value; }
	[JsonProperty("map_scale")]
	public double mapScale;
	[JsonProperty("annotation_scale")]
	public double annotationScale;
[JsonConverter(typeof(VisibilityConverter))]
	[JsonProperty("visibility")]
	public Visibility visibility;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"mapScale:" + mapScale + Environment.NewLine + 	"annotationScale:" + annotationScale + Environment.NewLine + 	"visibility:" + visibility + Environment.NewLine);
	}
	}
}