//
//  TourDocument.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class TourDocument: CoreObject, DocumentRelation {
	[Preserve]
	public enum Relation {
		MainImage,
		Media,
		Description
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			TourDocument.Relation castedValue = (TourDocument.Relation)value;
			switch (castedValue) {
			case TourDocument.Relation.MainImage:
			writer.WriteValue("MAIN_IMAGE");break;
			case TourDocument.Relation.Media:
			writer.WriteValue("MEDIA");break;
			case TourDocument.Relation.Description:
			writer.WriteValue("DESCRIPTION");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "MAIN_IMAGE":
			return TourDocument.Relation.MainImage;
			case "MEDIA":
			return TourDocument.Relation.Media;
			case "DESCRIPTION":
			return TourDocument.Relation.Description;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}