//
//  TourStopItemDocument.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class TourStopItemDocument: CoreObject, DocumentRelation {
	[Preserve]
	public enum Relation {
		Media,
		QuizCorrectChoiceMedia,
		QuizIncorrectChoiceMedia,
		QuizCorrectEvaluationMedia,
		QuizIncorrectEvaluationMedia
	}

	[Preserve]
	public class RelationConverter : JsonConverter {

		public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) {
			TourStopItemDocument.Relation castedValue = (TourStopItemDocument.Relation)value;
			switch (castedValue) {
			case TourStopItemDocument.Relation.Media:
			writer.WriteValue("MEDIA");break;
			case TourStopItemDocument.Relation.QuizCorrectChoiceMedia:
			writer.WriteValue("QUIZ_CORRECT_CHOICE_MEDIA");break;
			case TourStopItemDocument.Relation.QuizIncorrectChoiceMedia:
			writer.WriteValue("QUIZ_INCORRECT_CHOICE_MEDIA");break;
			case TourStopItemDocument.Relation.QuizCorrectEvaluationMedia:
			writer.WriteValue("QUIZ_CORRECT_EVALUATION_MEDIA");break;
			case TourStopItemDocument.Relation.QuizIncorrectEvaluationMedia:
			writer.WriteValue("QUIZ_INCORRECT_EVALUATION_MEDIA");break;
			}
		}

		public override object ReadJson(JsonReader reader, System.Type objectType, object existingValue, JsonSerializer serializer) {
			var enumString = (string)reader.Value;
			switch (enumString) {
			case "MEDIA":
			return TourStopItemDocument.Relation.Media;
			case "QUIZ_CORRECT_CHOICE_MEDIA":
			return TourStopItemDocument.Relation.QuizCorrectChoiceMedia;
			case "QUIZ_INCORRECT_CHOICE_MEDIA":
			return TourStopItemDocument.Relation.QuizIncorrectChoiceMedia;
			case "QUIZ_CORRECT_EVALUATION_MEDIA":
			return TourStopItemDocument.Relation.QuizCorrectEvaluationMedia;
			case "QUIZ_INCORRECT_EVALUATION_MEDIA":
			return TourStopItemDocument.Relation.QuizIncorrectEvaluationMedia;
			}
			return null;
		}

		public override bool CanConvert(System.Type objectType) {
			return objectType == typeof(string);
		}
	}

	[JsonProperty("priority")]
	private int internPriority;
	[JsonIgnore]
	public int priority { get => internPriority; set => internPriority = value; }
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("document_id")]
	private int internDocumentId;
	[JsonIgnore]
	public int documentId { get => internDocumentId; set => internDocumentId = value; }
[JsonConverter(typeof(RelationConverter))]
	[JsonProperty("relation")]
	public Relation relation;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"relation:" + relation + Environment.NewLine);
	}
	}
}