//
//  TourStop.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class TourStop: CoreObject, LegacyContent, Sorted {
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("subtitle")]
	private Dictionary<string, object> internSubtitle;
	[JsonIgnore]
	public Dictionary<string, object> subtitle { get => internSubtitle; set => internSubtitle = value; }
	[JsonProperty("subtitle_short")]
	private Dictionary<string, object> internSubtitleShort;
	[JsonIgnore]
	public Dictionary<string, object> subtitleShort { get => internSubtitleShort; set => internSubtitleShort = value; }
	[JsonProperty("title")]
	private Dictionary<string, object> internTitle;
	[JsonIgnore]
	public Dictionary<string, object> title { get => internTitle; set => internTitle = value; }
	[JsonProperty("title_short")]
	private Dictionary<string, object> internTitleShort;
	[JsonIgnore]
	public Dictionary<string, object> titleShort { get => internTitleShort; set => internTitleShort = value; }
	[JsonProperty("inventory_id")]
	private int internInventoryId;
	[JsonIgnore]
	public int inventoryId { get => internInventoryId; set => internInventoryId = value; }
	[JsonProperty("sort_index")]
	private int internSortIndex;
	[JsonIgnore]
	public int sortIndex { get => internSortIndex; set => internSortIndex = value; }
	[JsonProperty("tour_stop_items")]
	public TourStopItem[] tourStopItems;
	[JsonProperty("gp_zone_id")]
	public int gpZoneId;
	[JsonProperty("tour_stop_documents")]
	public TourStopDocument[] tourStopDocuments;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"tourStopItems:" + tourStopItems + Environment.NewLine + 	"gpZoneId:" + gpZoneId + Environment.NewLine + 	"tourStopDocuments:" + tourStopDocuments + Environment.NewLine);
	}
	}
}