//
//  UserFavorite.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using UnityEngine;
using UnityEngine.Scripting;


namespace com.guidepilot.guidepilotcore {
	[Preserve]
	public class UserFavorite: CoreObject {
	[JsonProperty("id")]
	private int internId;
	[JsonIgnore]
	public int id { get => internId; set => internId = value; }
	[JsonProperty("content_usage_suuid")]
	public string contentUsageSuuid;
	[JsonProperty("content_suuid")]
	public string contentSuuid;
	[JsonProperty("inventory_suuid")]
	public string inventorySuuid;
	[JsonProperty("created")]
	public DateTime created;
	public void print() {
		Debug.Log("object:" + Environment.NewLine + 	"contentUsageSuuid:" + contentUsageSuuid + Environment.NewLine + 	"contentSuuid:" + contentSuuid + Environment.NewLine + 	"inventorySuuid:" + inventorySuuid + Environment.NewLine + 	"created:" + created + Environment.NewLine);
	}
	}
}