//
//  Addressed.cs
//  GuidePilot
//
//  Allows the entity to store a address
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Addressed {
	 string addrStreet { get; set; }
	 string addrZipCode { get; set; }
	 string addrCity { get; set; }
	 string addrCountry { get; set; }
	}
}