//
//  Anchored.cs
//  GuidePilot
//
//  Describes a anchor in 3D space with a range of 0 to 1
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Anchored {
	 double? anchorH { get; set; }
	 double? anchorV { get; set; }
	 double? anchorZ { get; set; }
	}
}