//
//  Bounded.cs
//  GuidePilot
//
//  Describes a bounding box in 2D space without a restriction of the units.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Bounded: Positioned, Sized {
	}
}