//
//  Colored.cs
//  GuidePilot
//
//  Hints a color value for the appearance of the entity
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Colored {
	 string color { get; set; }
	}
}