//
//  ContextEvent.cs
//  GuidePilot
//
//  Interface for all analytics events that can be in session context
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface ContextEvent: RawEvent {
	 string sessionUuid { get; set; }
	 string installationUuid { get; set; }
	}
}