//
//  CoreLinkable.cs
//  GuidePilot
//
//  All objects should implement this.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface CoreLinkable {
	 string suuid { get; set; }
	}
}