//
//  Customized.cs
//  GuidePilot
//
//  Entities can have optional complex custom data
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Customized {
	 Dictionary<string, object> customData { get; set; }
	}
}