//
//  LegacyContent.cs
//  GuidePilot
//
//  
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface LegacyContent: CoreObject, Subtitled, Titled {
	 int inventoryId { get; set; }
	}
}