//
//  LocaleVisibility.cs
//  GuidePilot
//
//  Object that is only shown in specific locales
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface LocaleVisibility {
Language[] visibleInLocales { get; set; }
	}
}