//
//  Positioned.cs
//  GuidePilot
//
//  Describes a position in 2D space without a restriction of the units.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Positioned {
	 double? coordinateLeft { get; set; }
	 double? coordinateBottom { get; set; }
	}
}