//
//  Sized.cs
//  GuidePilot
//
//  Describes a size in 2D space without a restriction of the units.
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Sized {
	 double? coordinateWidth { get; set; }
	 double? coordinateHeight { get; set; }
	}
}