//
//  Subtitled.cs
//  GuidePilot
//
//  bla bla bla
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Subtitled {
	 Dictionary<string, object> subtitle { get; set; }
	 Dictionary<string, object> subtitleShort { get; set; }
	}
}