//
//  Titled.cs
//  GuidePilot
//
//  bla bla bla
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface Titled {
	 Dictionary<string, object> title { get; set; }
	 Dictionary<string, object> titleShort { get; set; }
	}
}