//
//  UiEvent.cs
//  GuidePilot
//
//  Interface for all analytics ui events
//
//  Generated by GuidePilot - EnumGenerator
//  Copyright © 2021 MicroMovie Media GmbH. All rights reserved.


using System;
using System.Collections.Generic;

namespace com.guidepilot.guidepilotcore {

	public interface UiEvent: ContextEvent, LocaleEvent {
	 string name { get; set; }
	}
}